### PR TITLE
Pull request for some small features.

### PR DESCRIPTION
**Pull request by martijnvg**
H Matt,

What do you think of the following additions:
- Added the option to specify an id for a document.
- Added q.dsl and fq.dsl options. Basically allows the ES query dsl inside the q and fq params.

Martijn

### CODE REVIEW

**Comment by mattweber** [comment]
Yea both of these are nice.  Can you refactor the pull request so SolrUpdateHandlerRestAction.java is only the changes you made?  It looks like the whitespace was updated so the commit looks like the entire file contents changed.

**Comment by martijnvg** [comment]
That looks weird... On my local machine I only see the changes for the lines that are actually changed. I look into it.

**Comment by martijnvg** [comment]
I noticed that in vi there was a ^m after every line in this file which wasn't in other files. So I used dos2unix to remove these end of line character. But the pull request still shows that for SolrUpdateHandlerRestAction all lines have been changed...

**Comment by martijnvg** [comment]
Phew... Seems to be fixed.

**Comment by mattweber** [comment]
Thanks, I rebased this into a single commit in master.

**Comment by martijnvg** [comment]
Nice!

**Pull request closed without merging**
